on:
  push:
    branches:
      - AG-1471

jobs:
  e2e:
    runs-on: ubuntu-latest
    environment: e2e
    env:
      CI: true
      PACKAGE_JSON_PATH: "package.json"
    steps:
      - uses: actions/checkout@v4
      - name: set data manifest id and version
        id: data-manifest
        run: |
          DATA_MANIFEST_ID=$(jq -r '."data-file"' "${{ env.PACKAGE_JSON_PATH }}")
          echo "DATA_MANIFEST_ID=${DATA_MANIFEST_ID}" >> "$GITHUB_ENV"

          DATA_VERSION=$(jq -r '."data-version"' "${{ env.PACKAGE_JSON_PATH }}")
          echo "DATA_VERSION=${DATA_VERSION}" >> "$GITHUB_ENV"
      - name: check whether image exists
        id: image-exists
        run: |
          echo "TODO - check if image exists:"
          echo "data manifest id: ${{ env.DATA_MANIFEST_ID }}"
          echo "data version: ${{ env.DATA_VERSION }}"
          echo "IMAGE_EXISTS=false" >> "$GITHUB_ENV"
      # https://github.com/actions/setup-python/issues/807
      - name: create placeholder requirements.txt file
        run: touch ./requirements.txt
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
          cache: 'pip'
      - name: install synapseclient
        run: |
          pip install --upgrade synapseclient
      - name: download data from synapse
        env: 
          DATA_DIR: './data'
          TEAM_IMAGES_DIR: './data/team_images'
          SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_AUTH_TOKEN }}
        run: |
          # make directory for team images
          mkdir -p "${{ env.TEAM_IMAGES_DIR }}"

          echo "check synapse download"
          synapse get --downloadLocation "${{ env.DATA_DIR }}" -v "1" "syn53701297"

          echo "list files"
          ls "${{ env.DATA_DIR }}"
